server:
  port: ${SPRING_PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DB_URL:192.170.0.100:5432}/${SPRING_DB_NAME:db_test_queue}
    username: ${SPRING_DB_USER:home_server_user}
    password: ${SPRING_DB_PASSWORD:157456}
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml